PRAGMA journal_mode = WAL;
PRAGMA busy_timeout = 5000;

CREATE TABLE IF NOT EXISTS text_input (
	id INTEGER PRIMARY KEY,
	content TEXT NOT NULL
) STRICT;

CREATE TABLE IF NOT EXISTS profile (
	name TEXT PRIMARY KEY,
	pk BLOB NOT NULL
) STRICT;

CREATE TABLE IF NOT EXISTS theme (
	name TEXT PRIMARY KEY,
	hue REAL NOT NULL,
	saturation REAL NOT NULL,
	brightness REAL NOT NULL,
	alpha REAL NOT NULL
) STRICT;

CREATE TABLE IF NOT EXISTS server (
	nick_name TEXT NOT NULL PRIMARY KEY,
	conn_string TEXT NOT NULL,
	pk BLOB NOT NULL
) STRICT;

CREATE TABLE IF NOT EXISTS asset (
	server BLOB NOT NULL,
	id INTEGER NOT NULL,
	name TEXT NOT NULL,
	type INTEGER NOT NULL,

	PRIMARY KEY (server, name)
) STRICT;
