PRAGMA journal_mode = WAL;
PRAGMA busy_timeout = 5000;

CREATE TABLE IF NOT EXISTS user (
	id INTEGER PRIMARY KEY,
	pk BLOB NOT NULL UNIQUE,
	name TEXT NOT NULL DEFAULT '',
	permissions INTEGER NOT NULL
) STRICT;

CREATE INDEX IF NOT EXISTS user_name ON user (name);
CREATE INDEX IF NOT EXISTS user_pk ON user (pk);

CREATE TABLE IF NOT EXISTS ip_sighting (
	user_id INTEGER NOT NULL,
	ip_lo INTEGER NOT NULL,
	ip_hi INTEGER NOT NULL,

	PRIMARY KEY (user_id, ip_lo, ip_hi),

	FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
) STRICT;

CREATE TABLE IF NOT EXISTS asset (
	id INTEGER NOT NULL,
	name TEXT NOT NULL,
	hash BLOB NOT NULL,
	size INTEGER NOT NULL,
	type INTEGER NOT NULL,
	visited INTEGER NOT NULL,

	PRIMARY KEY (name, type)
) STRICT;

UPDATE asset SET visited = 0;
