core:
  can_spawn_player: true
  physics:
    radius: 64
    sprite: core
  health:
    energy: 100
    energy_drain: -3
    recharge_speed: 2
    bind_range: 500
snipa:
  playable: true
  kind: Unit
  physics:
    speed: 1000
    friction: 2
    radius: 32
    sprite_factor_minus_one: 0.2
    sprite: blah
  attack:
    bullet: beam
  parry:
    invincibility: 0.3
    duration: 1
    cooldown: 1
    attack:
      bullets_per_shot_minus_one: 9
      innaccuracy: 1
      bullet: snip-shot
  turret:
    aim_speed: 8.1999998
    reload: 1
  health:
    energy: 30
    energy_drain: 1
    recharge_speed: 3
snip-shot:
  kind: Bullet
  physics:
    speed: 1000
    lifetime: 1
    radius: 8
    sprite_factor_minus_one: 0.3
    body_damage: 1
    lifetime_multiplier: 1
  trail:
    quantity_per_tick: 1
    particle:
      lifetime: 0.3
node:
  placable: true
  physics:
    radius: 32
    sprite: node
  health:
    energy: 15
    recharge_speed: 1
    bind_range: 400
turret:
  placable: true
  physics:
    radius: 64
    sprite: turret
  attack:
    innaccuracy: 0.2
    bullet: snip-shot
  turret:
    cannon: turrnat
    aim_speed: 6.28
    range: 500
    reload: 0.4
  health:
    energy: 30
    energy_drain: 1
    recharge_speed: 2
drill:
  placable: true
  physics:
    radius: 32
    sprite: drill
    spin: 3.14
  health:
    energy: 30
    energy_drain: -2
spawner:
  placable: true
  spawn_unit: snipa
  physics:
    radius: 32
    sprite: spawner
    spin: 1.65999997
  health:
    energy: 11
    recharge_speed: 2
laser:
  kind: Laser
  physics:
    speed: 1000
    lifetime: 0.2
    radius: 8
    body_damage: 4
beam:
  kind: Beam
  physics:
    speed: 600
    lifetime: 0.5
    radius: 8
    body_damage: 4
  trail:
    quantity_per_tick: 1
    particle:
      lifetime: 0.2
beamer:
  playable: true
  kind: Unit
  physics:
    speed: 300
    friction: 1
    radius: 32
    sprite: cannon
  attack:
    bullet: beam
  turret:
    reload: 1
